server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false

spring:
  h2:
    console:
      enabled: true
      settings:
        web-admin-password: example
        web-allow-others: true


database:
  url: jdbc:h2:file:./database/db_cards
  username: root
  password: root